"""Persistence boundary for favorites use cases."""

from contextlib import AbstractAsyncContextManager
from typing import Protocol
from uuid import UUID

from app.schemas.favorite import FavoriteResponse


class FavoriteRepository(Protocol):
    async def user_exists(self, user_id: UUID) -> bool: ...
    async def exercise_exists(self, exercise_id: UUID) -> bool: ...
    async def list_favorites(self, user_id: UUID) -> list[FavoriteResponse]: ...
    async def add(self, user_id: UUID, exercise_id: UUID) -> None: ...
    async def remove(self, user_id: UUID, exercise_id: UUID) -> None: ...
    async def ordered_ids(self, user_id: UUID) -> list[UUID]: ...
    async def reorder(self, user_id: UUID, exercise_ids: list[UUID]) -> None: ...


class FavoriteTransactions(Protocol):
    def transaction(
        self, *, write: bool = False
    ) -> AbstractAsyncContextManager[FavoriteRepository]: ...
